---
# file: roles/docker-exim4/tasks/main.yaml

# set the selinux policy to enable log-rotation of the exim4 logs
- import_tasks: selinux-docker-log_rotate.yml

# *****************************************************************************
# Setup the directory where the backup and restore is to take place

- name: restore dir
  file:
    state: directory
    path: '{{ host_exim4_docker_restore_dir }}'
    owner: root
    group: tape
    mode: 'u=rwx,g=rwx,o=rx'
    recurse: no
    setype: svirt_sandbox_file_t

- name: docker_container.conf dir
  file:
    state: directory
    path: '{{ docker_restore_config_base_dir }}/{{ exim4_dv_name }}'
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'
    recurse: no

# *****************************************************************************
# Setup the directory for the datavolume for the syslog data

- name: syslog dir
  file:
    state: directory
    path: '{{ exim4_syslog_datavolume_dir }}'
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'
    recurse: no
    setype: svirt_sandbox_file_t

- name: Create logrotate configuration for exim4
  template:
    src: dockercontainer.exim4.logrotate.j2
    dest: '/etc/logrotate.d/dockercontainer.{{ exim4_container_name }}'
  when: ansible_os_family == "RedHat"

# *****************************************************************************
# backup script part

- name: Assemble dir for backup scripts
  file:
    path: /usr/libexec/bacula/backup-scripts
    state: directory

- name: Create before_backup script
  template:
    src: before_backup.j2
    dest: /usr/libexec/bacula/backup-scripts/55.before_backup.exim4

- name: Create after_backup script
  template:
    src: after_backup.j2
    dest: /usr/libexec/bacula/backup-scripts/55.after_backup.exim4

# *****************************************************************************
# update the Docker restore config

- name: exists - state file
  stat:
    path: '{{ docker_restore_config_base_dir }}/{{ exim4_dv_name }}/restore.date.txt'
    get_checksum: False
    get_md5: False
  register: st_exim4_restore

# *****************************************************************************
# Update or make the image.

- name: build image
  docker_build:
    image_name: '{{ exim4_image_name }}'
    image_tag: '{{ docker_image_tag }}'
    dockerfile_dir: '{{ docker_projects_dir }}/docker-exim4'

# *****************************************************************************
# Create the data volumes

- name: data-volume container
  docker_datavolume:
    image_name: '{{ exim4_image_name }}'
    image_tag: '{{ docker_image_tag }}'
    data_volume_container_name: '{{ exim4_dv_name }}'

# *****************************************************************************
# Start the data container running

- name: start container
  docker_run:
    container_name: '{{ exim4_container_name }}'
    docker_run_arguments: '--hostname={{ container_addr_map.exim4.hostname }} {{ container_port_map.exim4.port_args }} -v {{ exim4_syslog_datavolume_dir }}/exim4:/var/log/exim4 --volumes-from {{ openssl_dv_name }} --volumes-from {{ exim4_dv_name }} {{ exim4_image_name }}:{{ docker_image_tag }}'

# *****************************************************************************
# restore?

- include_tasks: restore.yml
  when: st_exim4_restore.stat.exists == False

# *****************************************************************************
# Email accounts

- name: populate email passwords
  shell: 'docker run --rm --volumes-from {{ exim4_dv_name }} {{ exim4_image_name }}:{{ docker_image_tag }} add_account {{ item.value.user }} "{{ item.value.password }}"'
  with_dict: '{{ email_accounts }}'
