---

# The hostname passed as an envirnment variable into the container
container_addr_map:
  git:
    ip_addr: '127.0.0.1'
    hostname: git.example.com

# the port mappings used when starting the container
container_port_map:
  git:
    port_args: '-P'

# database usernames and passwords
gitlab_db_user: novatech

# must pass in the following variables
# gitlab_db_password: ''

# the name of the image being duilt and used for the container
gitlab_image_repo: 'https://github.com/novatechweb/docker-gitlab.git'
gitlab_image_name: '{{ docker_registry_username }}/gitlab'
gitlab_dv_image_name: '{{ docker_registry_username }}/gitlab'
gitlab_db_image_name: '{{ repository_images.postgres.image }}'
redis_image_name: '{{ repository_images.redis.image }}'

# the name of the gitlab container
gitlab_container_name: '{{ docker_name_prefix }}gitlab'

# the name of the redis container for gitlab
gitlab_redis_container_name: '{{ docker_name_prefix }}gitlab_redis'

# the name of the postgres container for gitlab
gitlab_db_container_name: '{{ docker_name_prefix }}gitlab_db'

# the name of the data-volume used by the container
gitlab_dv_name: '{{ docker_name_prefix }}gitlab_DV'

# the name of the data-volume used by the postgres container
gitlab_db_dv_name: '{{ docker_name_prefix }}gitlab_db_DV'

# restore directories to temporarly store data being restored into docker containers
gitlab_docker_backup_dir: '{{ docker_backup_dir }}/GIT'
host_gitlab_docker_restore_dir: '{{ bacula_dest }}{{ gitlab_docker_backup_dir }}'
