---
- assert:
    that:
    - bacula_director_password is defined
- name: Install/setup Bacula Console
  yum: name={{ item }} state=present
  with_items:
    - bacula-console
- name: Configure Bacula Console
  template: src=bconsole.conf.j2 dest={{ bacula_console_config_dir }}/bconsole.conf
          owner=bacula group=bacula mode=0640 backup=yes
