---
# file: roles/docker-mantisbt/tasks/restore.yaml

# *****************************************************************************
# Get data from tape

- name: exists - Static
  stat:
    path: '{{ host_mantisbt_docker_restore_dir }}{{ mantisbt_static_backup_file }}'
    get_checksum: False
    get_md5: False
  register: st_mantisbt_static_archive

- name: exists - SQL (files table)
  stat:
    path: '{{ host_mantisbt_docker_restore_dir }}{{ mantisbt_database_files_table_backup_file }}'
    get_checksum: False
    get_md5: False
  register: st_mantisbt_files_table_SQL_file

- name: exists - SQL (remaining tables)
  stat:
    path: '{{ host_mantisbt_docker_restore_dir }}{{ mantisbt_database_backup_file }}'
    get_checksum: False
    get_md5: False
  register: st_mantisbt_SQL_file

- name: data from tape
  bacula:
    command: restore
    storage: '{{ bacula_storage }}'
    fileset: '{{ bacula_fileset }}'
    dest: '{{ bacula_dest }}'
    path_to_restore: '{{ mantisbt_docker_backup_dir }}'
  when: st_mantisbt_static_archive.stat.exists == False or st_mantisbt_SQL_file.stat.exists == False or st_mantisbt_files_table_SQL_file.stat.exists == False

- name: permissions - Static
  file:
    path: '{{ host_mantisbt_docker_restore_dir }}{{ mantisbt_static_backup_file }}'
    state: touch
    owner: root
    group: root
    mode: 'u=rw,g=rw,o='

- name: permissions - SQL (files table)
  file:
    path: '{{ host_mantisbt_docker_restore_dir }}{{ mantisbt_database_files_table_backup_file }}'
    state: touch
    owner: root
    group: root
    mode: 'u=rw,g=rw,o='

- name: permissions - SQL (remaining tables)
  file:
    path: '{{ host_mantisbt_docker_restore_dir }}{{ mantisbt_database_backup_file }}'
    state: touch
    owner: root
    group: root
    mode: 'u=rw,g=rw,o='

- name: exists - Static
  stat:
    path: '{{ host_mantisbt_docker_restore_dir }}{{ mantisbt_static_backup_file }}'
    get_checksum: False
    get_md5: False
  register: st_mantisbt_static_archive

- name: exists - SQL (files table)
  stat:
    path: '{{ host_mantisbt_docker_restore_dir }}{{ mantisbt_database_files_table_backup_file }}'
    get_checksum: False
    get_md5: False
  register: st_mantisbt_files_table_SQL_file

- name: exists - SQL (remaining tables)
  stat:
    path: '{{ host_mantisbt_docker_restore_dir }}{{ mantisbt_database_backup_file }}'
    get_checksum: False
    get_md5: False
  register: st_mantisbt_SQL_file

# *****************************************************************************
# restore the mantisbt

- name: restore script
  command: '{{ docker_projects_dir }}/docker-mantisbt/mantisbt.sh restore -u {{ mantisbt_db_user }} -p {{ mantisbt_db_password | quote }}'
  args:
    chdir: '{{ docker_restore_config_base_dir }}/{{ mantisbt_dv_name }}/'
  when: st_mantisbt_static_archive.stat.exists == True and st_mantisbt_SQL_file.stat.exists == True and st_mantisbt_files_table_SQL_file.stat.exists == True

# *****************************************************************************
# cleanup

- name: Remove - Static and SQL
  file:
    path: '{{ host_mantisbt_docker_restore_dir }}'
    state: absent

- name: State file
  shell: 'date --rfc-3339=seconds > {{ docker_restore_config_base_dir }}/{{ mantisbt_dv_name }}/restore.date.txt'
  when: st_mantisbt_restore.stat.exists == False
