---
# file: roles/docker-openldap/tasks/restore.yaml

# *****************************************************************************
# Get data from tape

- name: find files
  files_in_dir:
    path: '{{ openldap_docker_restore_dir }}'
  register: openldap_backup

- name: Get data-volume data from tape
  bacula:
    command: restore
    storage: '{{ bacula_storage }}'
    fileset: '{{ bacula_fileset }}'
    dest: '{{ bacula_dest }}'
    path_to_restore: '{{ openldap_docker_backup_dir }}'
  when: openldap_backup.file_list == []

- name: Set permissions for data-volume data
  file:
    path: '{{ openldap_docker_restore_dir }}/{{ item.ldif_file }}'
    state: touch
    owner: root
    group: root
    mode: 'u=rw,g=rw,o='
  with_items: '{{ openldap_backup_files }}'

# *****************************************************************************
# restore the openldap backup

- name: stop container (ldap)
  command: 'docker stop {{ openldap_container_name }}'

- name: load ldif files
  command: 'docker run --rm --volumes-from {{ openldap_dv_name }} -v {{ host_openldap_docker_restore_dir }}:/tmp/import_export {{ openldap_image_name }}:{{ docker_image_tag }} apply_ldif -n {{ item.dbnum }} -l {{ item.ldif_file }}'
  with_items: '{{ openldap_backup_files }}'

- name: restart container (ldap)
  command: 'docker start {{ openldap_container_name }}'

# *****************************************************************************
# cleanup

- name: Remove database backup file
  file:
    path: '{{ openldap_docker_restore_dir }}'
    state: absent

- name: State file
  shell: 'date --rfc-3339=seconds > {{ docker_restore_config_base_dir }}/{{ openldap_dv_name }}/restore.date.txt'
  when: st_openldap_restore.stat.exists == False
