---

buildbot_version: '2.4.0'

buildbot_hostname: '{{ docker_name_prefix }}buildbot.novatech-llc.com'

buildbot_worker_port: '9989'

buildbot_certificate_not_before: '20200701000000Z'
buildbot_certificate_not_after: '20300701000000Z'

buildbot_ca_creds: '{{ playbook_dir + "/credentials/buildbot-ca" }}'
buildbot_ca_dir: '{{ buildbot_ca_creds }}'
buildbot_ca_csr: '{{ buildbot_ca_creds + "/ca.csr" }}'
buildbot_ca_key: '{{ buildbot_ca_creds + "/ca.key" }}'
buildbot_ca_pem: '{{ buildbot_ca_creds + "/ca.pem" }}'
buildbot_ca_fields:
  CN: cert_auth_ts.novatech-llc.com
  O: NovaTech
  OU: Orion
  C: US
  ST: Kansas
  L: Lenexa
  not_before: '{{ buildbot_certificate_not_before }}'
  not_after: '{{ buildbot_certificate_not_after }}'

buildbot_client_certificates:
  - dir: '{{ buildbot_creds }}'
    csr: '{{ buildbot_tlscsr }}'
    key: '{{ buildbot_tlskey }}'
    pem: '{{ buildbot_tlspem }}'
    fields:
      CN: '{{ buildbot_hostname }}'
      O: NovaTech
      OU: Orion
      C: US
      ST: Kansas
      L: Lenexa
      not_before: '{{ buildbot_certificate_not_before }}'
      not_after: '{{ buildbot_certificate_not_after }}'
  - dir: '{{ buildbot_worker_ntel_morty_creds }}'
    csr: '{{ buildbot_worker_ntel_morty_tlscsr }}'
    key: '{{ buildbot_worker_ntel_morty_tlskey }}'
    pem: '{{ buildbot_worker_ntel_morty_tlspem }}'
    fields:
      CN: buildbot-worker-ntel-morty'
      O: NovaTech
      OU: Orion
      C: US
      ST: Kansas
      L: Lenexa
      not_before: '{{ buildbot_certificate_not_before }}'
      not_after: '{{ buildbot_certificate_not_after }}'
  - dir: '{{ buildbot_worker_ntel_sumo_creds }}'
    csr: '{{ buildbot_worker_ntel_sumo_tlscsr }}'
    key: '{{ buildbot_worker_ntel_sumo_tlskey }}'
    pem: '{{ buildbot_worker_ntel_sumo_tlspem }}'
    fields:
      CN: buildbot-worker-ntel-sumo'
      O: NovaTech
      OU: Orion
      C: US
      ST: Kansas
      L: Lenexa
      not_before: '{{ buildbot_certificate_not_before }}'
      not_after: '{{ buildbot_certificate_not_after }}'
  - dir: '{{ buildbot_worker_ntel_warrior_creds }}'
    csr: '{{ buildbot_worker_ntel_warrior_tlscsr }}'
    key: '{{ buildbot_worker_ntel_warrior_tlskey }}'
    pem: '{{ buildbot_worker_ntel_warrior_tlspem }}'
    fields:
      CN: buildbot-worker-ntel-warrior'
      O: NovaTech
      OU: Orion
      C: US
      ST: Kansas
      L: Lenexa
      not_before: '{{ buildbot_certificate_not_before }}'
      not_after: '{{ buildbot_certificate_not_after }}'
  - dir: '{{ buildbot_worker_ptxdist_creds }}'
    csr: '{{ buildbot_worker_ptxdist_tlscsr }}'
    key: '{{ buildbot_worker_ptxdist_tlskey }}'
    pem: '{{ buildbot_worker_ptxdist_tlspem }}'
    fields:
      CN: buildbot-worker-ptxdist
      O: NovaTech
      OU: Orion
      C: US
      ST: Kansas
      L: Lenexa
      not_before: '{{ buildbot_certificate_not_before }}'
      not_after: '{{ buildbot_certificate_not_after }}'

buildbot_ssh_clients:
  - dir: '{{ buildbot_creds }}'
    sshkey: '{{ buildbot_sshkey }}'
    username: buildbot
    name: Build Robot
    email: buildbot@novatech-llc.com
    password: "{{ gitlab_user_buildbot_password }}"
    sshkey_name: "{{ docker_name_prefix }}buildbot_master"
  - dir: '{{ buildbot_worker_ntel_morty_creds }}'
    sshkey: '{{ buildbot_worker_ntel_morty_sshkey }}'
    username: buildbot
    name: Build Robot
    email: buildbot@novatech-llc.com
    password: "{{ gitlab_user_buildbot_password }}"
    sshkey_name: "{{ docker_name_prefix }}buildbot_worker_ntel_morty"
  - dir: '{{ buildbot_worker_ntel_sumo_creds }}'
    sshkey: '{{ buildbot_worker_ntel_sumo_sshkey }}'
    username: buildbot
    name: Build Robot
    email: buildbot@novatech-llc.com
    password: "{{ gitlab_user_buildbot_password }}"
    sshkey_name: "{{ docker_name_prefix }}buildbot_worker_ntel_sumo"
  - dir: '{{ buildbot_worker_ntel_warrior_creds }}'
    sshkey: '{{ buildbot_worker_ntel_warrior_sshkey }}'
    username: buildbot
    name: Build Robot
    email: buildbot@novatech-llc.com
    password: "{{ gitlab_user_buildbot_password }}"
    sshkey_name: "{{ docker_name_prefix }}buildbot_worker_ntel_warrior"
  - dir: '{{ buildbot_worker_ptxdist_creds }}'
    sshkey: '{{ buildbot_worker_ptxdist_sshkey }}'
    username: buildbot
    name: Build Robot
    email: buildbot@novatech-llc.com
    password: "{{ gitlab_user_buildbot_password }}"
    sshkey_name: "{{ docker_name_prefix }}buildbot_worker_ptxdist"

buildbot_gitlab_groups:
  - group: "Orion-Userspace"
    access_level: "developer"
    username: buildbot
    name: Build Robot
    email: buildbot@novatech-llc.com
    password: "{{ gitlab_user_buildbot_password }}"
  - group: "Orion"
    access_level: "developer"
    username: buildbot
    name: Build Robot
    email: buildbot@novatech-llc.com
    password: "{{ gitlab_user_buildbot_password }}"
  - group: "ntel"
    access_level: "developer"
    username: buildbot
    name: Build Robot
    email: buildbot@novatech-llc.com
    password: "{{ gitlab_user_buildbot_password }}"
  - group: "Orion-ptxdist"
    access_level: "developer"
    username: buildbot
    name: Build Robot
    email: buildbot@novatech-llc.com
    password: "{{ gitlab_user_buildbot_password }}"

buildbot_gitlab_hooks:
  - hook_url: "http://{{ buildbot_hostname }}:{{ buildbot_http_port }}/change_hook/gitlab"
    project: ntel/setup-scripts
    token: "{{ buildbot_webhook_secret }}"
    hook_validate_certs: yes
    merge_requests_events: yes
    push_events: yes
  - hook_url: "http://{{ buildbot_hostname }}:{{ buildbot_http_port }}/change_hook/gitlab"
    project: ntel/meta-ntel
    token: "{{ buildbot_webhook_secret }}"
    hook_validate_certs: yes
    merge_requests_events: yes
    push_events: yes
  - hook_url: "http://{{ buildbot_hostname }}:{{ buildbot_http_port }}/change_hook/gitlab"
    project: ntel/meta-orion-bsp
    token: "{{ buildbot_webhook_secret }}"
    hook_validate_certs: yes
    merge_requests_events: yes
    push_events: yes
  - hook_url: "http://{{ buildbot_hostname }}:{{ buildbot_http_port }}/change_hook/gitlab"
    project: ntel/meta-backports
    token: "{{ buildbot_webhook_secret }}"
    hook_validate_certs: yes
    merge_requests_events: yes
    push_events: yes
  - hook_url: "http://{{ buildbot_hostname }}:{{ buildbot_http_port }}/change_hook/gitlab"
    project: ntel/meta-copalp
    token: "{{ buildbot_webhook_secret }}"
    hook_validate_certs: yes
    merge_requests_events: yes
    push_events: yes
  - hook_url: "http://{{ buildbot_hostname }}:{{ buildbot_http_port }}/change_hook/gitlab"
    project: ntel/meta-orion
    token: "{{ buildbot_webhook_secret }}"
    hook_validate_certs: yes
    merge_requests_events: yes
    push_events: yes
  - hook_url: "http://{{ buildbot_hostname }}:{{ buildbot_http_port }}/change_hook/gitlab"
    project: ntel/meta-sssd
    token: "{{ buildbot_webhook_secret }}"
    hook_validate_certs: yes
    merge_requests_events: yes
    push_events: yes
  - hook_url: "http://{{ buildbot_hostname }}:{{ buildbot_http_port }}/change_hook/gitlab"
    project: ntel/meta-mz-automation
    token: "{{ buildbot_webhook_secret }}"
    hook_validate_certs: yes
    merge_requests_events: yes
    push_events: yes
  - hook_url: "http://{{ buildbot_hostname }}:{{ buildbot_http_port }}/change_hook/gitlab"
    project: forks/meta-selinux
    token: "{{ buildbot_webhook_secret }}"
    hook_validate_certs: yes
    merge_requests_events: yes
    push_events: yes
  - hook_url: "http://{{ buildbot_hostname }}:{{ buildbot_http_port }}/change_hook/gitlab"
    project: forks/meta-mingw
    token: "{{ buildbot_webhook_secret }}"
    hook_validate_certs: yes
    merge_requests_events: yes
    push_events: yes

buildbot_creds: '{{ playbook_dir + "/credentials/buildbot" }}'
buildbot_sshkey: '{{ buildbot_creds }}/id_rsa'
buildbot_tlsca:  '{{ buildbot_ca_pem }}'
buildbot_tlscsr: '{{ buildbot_creds }}/server.csr'
buildbot_tlskey: '{{ buildbot_creds }}/server.key'
buildbot_tlspem: '{{ buildbot_creds }}/server.pem'

buildbot_email_password: '{{ lookup("password", buildbot_creds + "/buildbot@novatech-llc.com length=20 chars=ascii_letters,digits") }}'

# environment passed to the container
buildbot_env:
  BUILDBOT_DATABASE: 'sqlite:///{{ buildbot_data_path }}/state.sqlite'
  BUILDBOT_SMTP_HOST: '{{ exim4_hostname }}'
  BUILDBOT_SMTP_PORT: '587'
  BUILDBOT_SMTP_USER: 'buildbot'
  BUILDBOT_SMTP_PASS: '{{ buildbot_email_password }}'
  BUILDBOT_WEB_PORT: '{{ buildbot_http_port }}'
  BUILDBOT_WEB_URL: 'https://{{ buildbot_hostname }}/'
  BUILDBOT_WORKER_PORT: '{{ buildbot_connection_string }}'
  BUILDBOT_WORKER_NTEL_MORTY_BETA_URI: '{{ ntel_beta_uri }}'
  BUILDBOT_WORKER_NTEL_MORTY_NAME: '{{ buildbot_worker_ntel_morty }}'
  BUILDBOT_WORKER_NTEL_MORTY_PASS: '{{ buildbot_worker_ntel_morty_passwd }}'
  BUILDBOT_WORKER_NTEL_MORTY_RELEASE_URI: '{{ ntel_release_uri }}'
  BUILDBOT_WORKER_NTEL_MORTY_SSTATE_URI: '{{ ntel_sstate_uri }}'
  BUILDBOT_WORKER_NTEL_SUMO_BETA_URI: '{{ ntel_beta_uri }}'
  BUILDBOT_WORKER_NTEL_SUMO_NAME: '{{ buildbot_worker_ntel_sumo }}'
  BUILDBOT_WORKER_NTEL_SUMO_PASS: '{{ buildbot_worker_ntel_sumo_passwd }}'
  BUILDBOT_WORKER_NTEL_SUMO_RELEASE_URI: '{{ ntel_release_uri }}'
  BUILDBOT_WORKER_NTEL_SUMO_SSTATE_URI: '{{ ntel_sstate_uri }}'
  BUILDBOT_WORKER_NTEL_WARRIOR_BETA_URI: '{{ ntel_beta_uri }}'
  BUILDBOT_WORKER_NTEL_WARRIOR_NAME: '{{ buildbot_worker_ntel_warrior }}'
  BUILDBOT_WORKER_NTEL_WARRIOR_PASS: '{{ buildbot_worker_ntel_warrior_passwd }}'
  BUILDBOT_WORKER_NTEL_WARRIOR_RELEASE_URI: '{{ ntel_release_uri }}'
  BUILDBOT_WORKER_NTEL_WARRIOR_SSTATE_URI: '{{ ntel_sstate_uri }}'
  BUILDBOT_WORKER_PTXDIST_BETA_URI: '{{ ptxdist_beta_uri }}'
  BUILDBOT_WORKER_PTXDIST_NAME: '{{ buildbot_worker_ptxdist }}'
  BUILDBOT_WORKER_PTXDIST_PASS: '{{ buildbot_worker_ptxdist_passwd }}'
  BUILDBOT_WORKER_PTXDIST_RELEASE_URI: '{{ ptxdist_release_uri }}'
  GITLAB_URI: 'https://{{ gitlab_hostname }}/'
  GITLAB_OAUTH_ID: '{{ gitlab_oauth_buildbot_id }}'
  GITLAB_OAUTH_SECRET: '{{ gitlab_oauth_buildbot_secret }}'
  GITLAB_TOKEN: '{{ gitlab_user_buildbot_token }}'
  GITLAB_WEBHOOK_SECRET: '{{ buildbot_webhook_secret }}'
  LDAP_URI: 'ldap://{{ openldap_hostname }}:389/'
  LDAP_BIND_USER: 'cn=proxyagent,dc=novatech'
  LDAP_BIND_PW: '{{ openldap_proxyagent_password }}'

buildbot_image_dir: '{{ docker_projects_dir }}/buildbot-master'
buildbot_image_name: '{{ docker_registry_username }}/buildbot:{{ docker_image_tag }}'

buildbot_name: '{{ docker_name_prefix }}buildbot'

buildbot_networks:
  - name: '{{ docker_network_frontend }}'
    aliases:
    - '{{ buildbot_hostname }}'

buildbot_hostdir_config: '{{ docker_restore_config_base_dir }}/buildbot'
buildbot_hostdir_config_ssl: '{{ buildbot_hostdir_config }}/ssl'

buildbot_worker_configs:
  - module: 'worker_ntel_morty'
    giturl: 'git@{{ gitlab_hostname }}:ntel/setup-scripts'
    branch: 'morty'
  - module: 'worker_ntel_sumo'
    giturl: 'git@{{ gitlab_hostname }}:ntel/setup-scripts'
    branch: 'sumo'
  - module: 'worker_ntel_warrior'
    giturl: 'git@{{ gitlab_hostname }}:ntel/setup-scripts'
    branch: 'warrior'
  - module: 'worker_ptxdist_master'
    giturl: 'git@{{ gitlab_hostname }}:Orion-ptxdist/workspace-ptxdist2'
    branch: 'master'

buildbot_worker_network: '{{ docker_name_prefix }}workers'
buildbot_worker_networks:
  - name: '{{ buildbot_worker_network }}'
    aliases:
      - '{{ buildbot_worker_hostname }}'

buildbot_worker_image_dir: '{{ docker_projects_dir }}/{{ buildbot_worker_container }}'
buildbot_worker_image_name: '{{ docker_registry_username }}/{{ buildbot_worker_container }}:{{ docker_image_tag }}'

buildbot_worker_ntel_morty: '{{ docker_name_prefix }}buildbot-worker-ntel-morty'
buildbot_worker_ntel_morty_hostdir_config: '{{ docker_restore_config_base_dir }}/buildbot-worker-ntel-morty'
buildbot_worker_ntel_morty_hostdir_ssl: '{{ buildbot_worker_ntel_morty_hostdir_config }}/ssl'
buildbot_worker_ntel_morty_creds: '{{ playbook_dir }}/credentials/buildbot-worker-ntel-morty'
buildbot_worker_ntel_morty_passwd: '{{ lookup("password", buildbot_worker_ntel_morty_creds + "/passwd length=20") }}'
buildbot_worker_ntel_morty_sshkey: '{{ buildbot_worker_ntel_morty_creds }}/id_rsa'
buildbot_worker_ntel_morty_tlscsr: '{{ buildbot_worker_ntel_morty_creds }}/worker.csr'
buildbot_worker_ntel_morty_tlspem: '{{ buildbot_worker_ntel_morty_creds }}/worker.pem'
buildbot_worker_ntel_morty_tlskey: '{{ buildbot_worker_ntel_morty_creds }}/worker.key'

buildbot_worker_ntel_sumo: '{{ docker_name_prefix }}buildbot-worker-ntel-sumo'
buildbot_worker_ntel_sumo_hostdir_config: '{{ docker_restore_config_base_dir }}/buildbot-worker-ntel-sumo'
buildbot_worker_ntel_sumo_hostdir_ssl: '{{ buildbot_worker_ntel_sumo_hostdir_config }}/ssl'
buildbot_worker_ntel_sumo_creds: '{{ playbook_dir }}/credentials/buildbot-worker-ntel-sumo'
buildbot_worker_ntel_sumo_passwd: '{{ lookup("password", buildbot_worker_ntel_sumo_creds + "/passwd length=20") }}'
buildbot_worker_ntel_sumo_sshkey: '{{ buildbot_worker_ntel_sumo_creds }}/id_rsa'
buildbot_worker_ntel_sumo_tlscsr: '{{ buildbot_worker_ntel_sumo_creds }}/worker.csr'
buildbot_worker_ntel_sumo_tlspem: '{{ buildbot_worker_ntel_sumo_creds }}/worker.pem'
buildbot_worker_ntel_sumo_tlskey: '{{ buildbot_worker_ntel_sumo_creds }}/worker.key'

buildbot_worker_ntel_warrior: '{{ docker_name_prefix }}buildbot-worker-ntel-warrior'
buildbot_worker_ntel_warrior_hostdir_config: '{{ docker_restore_config_base_dir }}/buildbot-worker-ntel-warrior'
buildbot_worker_ntel_warrior_hostdir_ssl: '{{ buildbot_worker_ntel_warrior_hostdir_config }}/ssl'
buildbot_worker_ntel_warrior_creds: '{{ playbook_dir }}/credentials/buildbot-worker-ntel-warrior'
buildbot_worker_ntel_warrior_passwd: '{{ lookup("password", buildbot_worker_ntel_warrior_creds + "/passwd length=20") }}'
buildbot_worker_ntel_warrior_sshkey: '{{ buildbot_worker_ntel_warrior_creds }}/id_rsa'
buildbot_worker_ntel_warrior_tlscsr: '{{ buildbot_worker_ntel_warrior_creds }}/worker.csr'
buildbot_worker_ntel_warrior_tlspem: '{{ buildbot_worker_ntel_warrior_creds }}/worker.pem'
buildbot_worker_ntel_warrior_tlskey: '{{ buildbot_worker_ntel_warrior_creds }}/worker.key'

buildbot_worker_ptxdist: '{{ docker_name_prefix }}buildbot-worker-ptxdist'
buildbot_worker_ptxdist_hostdir_config: '{{ docker_restore_config_base_dir }}/buildbot-worker-ptxdist'
buildbot_worker_ptxdist_hostdir_ssl: '{{ buildbot_worker_ptxdist_hostdir_config }}/ssl'
buildbot_worker_ptxdist_creds: '{{ playbook_dir }}/credentials/buildbot-worker-ptxdist'
buildbot_worker_ptxdist_passwd: '{{ lookup("password", buildbot_worker_ptxdist_creds + "/passwd length=20") }}'
buildbot_worker_ptxdist_sshkey: '{{ buildbot_worker_ptxdist_creds }}/id_rsa'
buildbot_worker_ptxdist_tlscsr: '{{ buildbot_worker_ptxdist_creds }}/worker.csr'
buildbot_worker_ptxdist_tlskey: '{{ buildbot_worker_ptxdist_creds }}/worker.key'
buildbot_worker_ptxdist_tlspem: '{{ buildbot_worker_ptxdist_creds }}/worker.pem'

buildbot_webhook_secret: '{{ lookup("password", buildbot_creds + "/webhook length=20") }}'

ntel_beta_uri:       "https://{{ nexus_hostname }}/repository/ntel-unofficial"
ntel_release_uri:    "https://{{ nexus_hostname }}/repository/ntel-release"
ntel_sstate_uri:     "https://{{ nexus_hostname }}/repository/ntel-sstate"
ptxdist_beta_uri:    "https://{{ nexus_hostname }}/repository/ptxdist-unofficial"
ptxdist_release_uri: "https://{{ nexus_hostname }}/repository/ptxdist-release"
