---

# The tag of the immage currently being used to build the container
docker_image_tag: production

# A prefix to seperate containers and images without removing running containers
docker_name_prefix: ''

# the user name portion of the docker image name
docker_registry_username: novatechweb

# the base directory where the docker projects will be checked out
docker_projects_dir: '/opt/docker/{{ docker_image_tag }}'
docker_restore_config_base_dir: '/etc/docker_container.conf/{{ docker_image_tag }}'

# restore directories to temporarly store data being restored into docker containers
docker_backup_dir: '/tmp/docker'
