---

svn_hostname: svn.novatech-llc.com
svn_port_args:
- "{{ svn_ip_addr }}:80:80"
- "{{ svn_ip_addr }}:443:443"

gitlab_hostname: git.novatech-llc.com
gitlab_port_args:
- "{{ gitlab_ip_addr }}:80:80"
- "{{ gitlab_ip_addr }}:443:443"
- "{{ gitlab_ip_addr }}:22:22"

wiki_hostname: wiki.novatech-llc.com
wiki_port_args:
- "{{ wiki_ip_addr }}:80:80"
- "{{ wiki_ip_addr }}:443:443"

mantisbt_hostname: mantis.novatech-llc.com
mantisbt_port_args:
- "{{ mantisbt_ip_addr }}:80:80"
- "{{ mantisbt_ip_addr }}:443:443"

build_hostname: buildsystem.novatech-llc.com
build_port_args:
- "{{ build_ip_addr }}:80:80"
- "{{ build_ip_addr }}:443:443"

testssh_hostname: testssh.novatech-llc.com
testssh_port_args:
- "{{ testssh_ip_addr }}:2200:22"

exim4_hostname: mail.novatech-llc.com
exim4_port_args:
- "{{ exim4_ip_addr }}:25:25"
- "{{ exim4_ip_addr }}:465:465"
- "{{ exim4_ip_addr }}:587:587"

openldap_hostname: ldap.novatech-llc.com
openldap_port_args:
- "{{ openldap_ip_addr }}:389:389"
- "{{ openldap_ip_addr }}:636:636"

phpldapadmin_hostname: ldap.novatech-llc.com
phpldapadmin_port_args: []

phpmyadmin_hostname: phpmyadmin.novatech-llc.com

buildbot_hostname: buildbot.novatech-llc.com
buildbot_port_args:
- "{{ buildbot_ip_addr }}:9989:9989"

nexus_hostname: nexus.novatech-llc.com
nexus_port_args: []

haproxy_port_args:
- "{{ ansible_facts.default_ipv4.address }}:80:80"
- "{{ ansible_facts.default_ipv4.address }}:443:443"
- "{{ ansible_facts.default_ipv4.address }}:9000:9000"
- "{{ buildbot_ip_addr }}:80:80"
- "{{ buildbot_ip_addr }}:443:443"
- "{{ nexus_ip_addr }}:80:80"
- "{{ nexus_ip_addr }}:443:443"
- "{{ phpldapadmin_ip_addr }}:80:80"
- "{{ phpldapadmin_ip_addr }}:443:443"

ddio_hostname: ddio.novatech-llc.com
ddio_port_args: []

easyrsa_hostname: easyrsa.novatech-llc.com
easyrsa_port_args:
- "{{ easyrsa_ip_addr }}:22:22"
