---
#=========================================================
# Backup Service Container
#---------------------------------------------------------
# This sets needed enviroments for the docker image varibles and builds said image.  The running/starting of the backup
#   is done by the bacula service when it runs. Running/starting of the restore is done in the 'tasks/restore.yml'
#   which is called in the 'tasks/restore.yml'.
#---------------------------------------------------------

- name: Setting db password used to access MySQL DB's
  replace:
    dest: "{{ docker_projects_dir }}/{{ build_system_docker_repos.Backup_Restore.dir_name }}/Dockerfile"
    regexp: '(ENV\s+DATABASE_PASSWORD\s+).*'
    replace: '\1 {{ buildsystem_database_root_password }}'

- name: Build docker image ----- Test Station Backup service
  docker_image:
    name: "{{ name_prefix }}teststation_supportsite_backup_restore_image"
    path: "{{ docker_projects_dir }}/{{ build_system_docker_repos.Backup_Restore.dir_name }}"
    state: "{{ image_build_state_nondata }}"
    force: "{{ docker_image_force_build }}"
