---
#=========================================================
# CRON Service Container
#---------------------------------------------------------
- name: Build docker image ----- Test Station cron service
  docker_image:
    name: "{{ name_prefix }}teststation_cron_image"
    path: "{{ docker_projects_dir }}/{{ build_system_docker_repos.TestStation_cron_service.dir_name }}"
    state: "{{ image_build_state_nondata }}"

- name: Start docker container - Test Station cron service
  docker_container:
    detach: True
    image: "{{ name_prefix }}teststation_cron_image"
    name: "{{ name_prefix }}TestStation_cron_service"
    state: "{{ container_start_state_nondata }}"
    restart_policy: always
    volumes_from:
      - "{{ name_prefix }}TestStation_http_data_ncdiso"
