---
# file: roles/docker-common/tasks/ip_addr.yaml

- name: Make an IP address available
  template:
    src: ifcfg-br0.j2
    dest: '/etc/sysconfig/network-scripts/ifcfg-br0:{{ item.value.bridge_num }}'
    backup: no
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
  when: ansible_os_family == "RedHat"
  when: (item.value.bridge_num is not undefined) and (ansible_os_family == "RedHat")
  with_dict: container_addr_map

- name: add container hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '{{ item.value.ip_addr }}	.*$'
    line: "{{ item.value.ip_addr }}	{{ item.value.hostname }}"
    state: present
  when: item.value.bridge_num is not undefined
  with_dict: container_addr_map

- name: enable ip forwarding
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: '.*net.ipv4.ip_forward.*$'
    line: "net.ipv4.ip_forward = 1"
    state: present
  when: ansible_os_family == "RedHat"

- name: make IPs active
  service:
    name: network
    state: restarted
  when: ansible_os_family == "RedHat"

- name: make IPs active (second attempt)
  service:
    name: network
    state: restarted
  when: ansible_os_family == "RedHat"
