---
# file: roles/docker-common/tasks/main.yaml

- import_tasks: engine-redhat.yml
  when: ansible_facts.os_family == "RedHat"

- import_tasks: engine-debian.yml
  when: ansible_facts.os_family == "Debian"

- name: Start docker service
  service:
    name: docker
    enabled: yes
    state: started

- import_tasks: packages.yml

- import_tasks: configure.yml


# *****************************************************************************
# Install selinux policies

- import_tasks: selinux-bacula-policy.yml

- import_tasks: selinux-setlink-policy.yml

- import_tasks: selinux-signals-policy.yml
