---
# file: roles/docker-common/tasks/main.yaml

- import_tasks: engine-redhat.yml
  when: ansible_os_family == "RedHat"

- import_tasks: packages.yml
- import_tasks: sshd_settings.yml
- import_tasks: mariadb_settings.yml

- import_tasks: configure.yml


- name: Check if baculavirt selinux module exists
  stat:
    path: /etc/selinux/targeted/modules/active/modules/docker_bacula.pp
  register: docker_bacula_pp
  when: ansible_os_family == "RedHat"

- include_tasks: selinux-backula-policy.yml
  when: (docker_bacula_pp.stat.exists is defined) and (docker_bacula_pp.stat.exists == false)
