---
# defaults file for buildbot-master

# numeric version of buildbot service
buildbot_version: '2.4.0'

buildbot_connection_string: "\
  ssl\
  :port={{ buildbot_worker_port }}\
  :sslmethod=TLSv1_2_METHOD\
  :certKey={{ buildbot_ssl_dir }}/{{ master_tlspem }}\
  :privateKey={{ buildbot_ssl_dir }}/{{ master_tlskey }}\
  :extraCertChain={{ buildbot_ssl_dir }}/{{ master_tlsca }}"

# name of the data volume
buildbot_volume_data: 'buildbot_DV'

# environment passed to the container
buildbot_env:
  BUILDBOT_DATABASE: 'sqlite:///{{ buildbot_data_path }}/state.sqlite'
  BUILDBOT_WEB_PORT: '{{ buildbot_http_port }}'
  BUILDBOT_WEB_URL: 'https://{{ buildbot_hostname }}/'
  BUILDBOT_WORKER_PORT: '{{ buildbot_connection_string }}'

# host path containing configuration files
buildbot_hostdir_config: '/etc/buildbot-master'

# directory for TLS certificates
buildbot_hostdir_ssl: '{{ buildbot_hostdir_config }}/ssl'

# hostname
buildbot_hostname: buildbot.example.com

# port number for unencrypted web access
buildbot_http_port: '8080'

# build arguments of the image
buildbot_image_args:
  BUILDBOT_TIMEZONE: 'America/Chicago'
  BUILDBOT_UID: '{{ buildbot_uid }}'
  BUILDBOT_VERSION: 'v{{ buildbot_version }}'
  BUILDBOT_WORKDIR: '{{ buildbot_data_path }}'

# directory of the image source
buildbot_image_dir: '/tmp/buildbot-master'

# name of the image being built
buildbot_image_name: 'buildbot:latest'

# list of ssh hosts known to the container
known_hosts: ''

# the name of the container being started
buildbot_name: 'buildbot'

# networks of the container
buildbot_networks:
  - name: 'bridge'

# exposed ports of the container
buildbot_port_args:
  - '{{buildbot_http_port}}'
  - '{{buildbot_worker_port}}'

# how the container should restart upon errors
buildbot_restart_policy: 'no'

buildbot_tlsca: '{{ buildbot_hostdir_ssl }}/{{ master_tlsca }}'
buildbot_tlskey: '{{ buildbot_hostdir_ssl }}/{{ master_tlskey }}'
buildbot_tlspem: '{{ buildbot_hostdir_ssl }}/{{ master_tlspem }}'

# volumes mounted within the container
buildbot_volumes:
  - '{{ buildbot_volume_data }}:{{ buildbot_data_path }}:z'
  - '{{ buildbot_hostdir_config }}/buildbot.tac:{{ buildbot_tac_file }}:ro'
  - '{{ buildbot_hostdir_config }}/master.cfg:{{ buildbot_cfg_file }}:ro'
  - '{{ buildbot_hostdir_config }}/novatech.py:{{ buildbot_data_path }}/novatech.py'
  - '{{ buildbot_hostdir_config }}/{{ buildbot_sshkey }}:{{ buildbot_ssh_id_file }}:ro'
  - '{{ buildbot_hostdir_config }}/known_hosts:{{ buildbot_known_hosts }}:ro'
  - '{{ buildbot_hostdir_ssl }}:{{ buildbot_ssl_dir }}:ro'

# port number for workers to communicate with master
buildbot_worker_port: '9989'
